export const FETCH_GAMES_START='FETCH_GAMES_START'
export const FETCH_GAMES_SUCCESS='FETCH_GAMES_SUCCESS'
export const FETCH_GAMES_FAIL='FETCH_GAMES_FAIL'

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';


export const LIKE_GAME_START='LIKE_GAME_START'
export const LIKE_GAME_SUCCESS='LIKE_GAME_SUCCESS'
export const LIKE_GAME_FAIL='LIKE_GAME_FAIL'


export const DISLIKE_GAME_START='DISLIKE_GAME_START'
export const DISLIKE_GAME_SUCCESS='DISLIKE_GAME_SUCCESS'
export const DISLIKE_GAME_FAIL='DISLIKE_GAME_FAIL'

export const FETCH_LIKES_START='FETCH_LIKES_START'
export const FETCH_LIKES_SUCCESS='FETCH_LIKES_SUCCESS'
export const FETCH_LIKES_FAIL='FETCH_LIKES_FAIL'