export const FETCH_GAMES_START='FETCH_GAMES_START'
export const FETCH_GAMES_SUCCESS='FETCH_GAMES_SUCCESS'
export const FETCH_GAMES_FAIL='FETCH_GAMES_FAIL'

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';